### PR TITLE
Update libcurl-7.40.0

### PR DESCRIPTION
**Pull request by brocolis**
@AndrewEdwards 
@braddr 
@eco

http://d.darktech.org/libcurl-7.40.0-WinSSL-zlib-x86-x64.zip
MD5: ec3a0bd6bb3e227dae99a8e81cba42c1

Please upload it to http://downloads.dlang.org/other/

### CODE REVIEW

**Comment by MartinNowak** [comment]
Thanks, please wait with the merge until it's uploaded.

**Comment by andralex** [comment]
cc @braddr again :)

**Comment by braddr** [comment]
Uploaded to downloads.dlang.org.  For what it's worth, github cc'ing is a really bad way to reach me.  Way too much chance I won't see it, or at least not rapidly.

**Comment by andralex** [comment]
@braddr thx!

**Comment by MartinNowak** [comment]
Thx

> For what it's worth, github cc'ing is a really bad way to reach me. Way too much chance I won't see it, or at least not rapidly.

What's a good way to reach you then?

**Pull request merged**
