### PR TITLE
Fix issue 14801: OS X installer not compatible with OS X 10.11

### PR DESCRIPTION
**Pull request by jacob-carlborg**
In the upcoming OS X 10.11 /usr is not writable. Instead the compiler
is installed in /Library/D/dmd and symlinked to /usr/local.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Thanks a lot Jacob.
It seems that the symlinks make things more complex w/o any benefit, why not use the classical UNIX folders?
If we'd want to use a single dmd folder, I'd prefer /use/local/dmd over /Library/D b/c the library folder contains all the Apple frameworks.

**Comment by jacob-carlborg** [comment]
Short answer: the is only a fix for the installer not working on OS X 10.11, this was easiest to do. /Libraries contains other things as well, Ruby and Perl for example.

**Comment by MartinNowak** [comment]
> /Libraries contains other things as well, Ruby and Perl for example.

Aren't those the versions preinstalled by Apple. Let's go on with this though.
[OS X Mavericks: What is the Library folder?](https://support.apple.com/kb/PH14330?locale=en_US)

**Comment by MartinNowak** [comment]
Should have targeted the stable branch btw.

**Comment by jacob-carlborg** [comment]
> Should have targeted the stable branch btw

Ah, sorry. I'm not familiar with how the stable branches are used in the D projects.

**Comment by MartinNowak** [comment]
Did you actually test this change?
https://issues.dlang.org/show_bug.cgi?id=14801#c12

**Comment by MartinNowak** [comment]
see #133

**Comment by jacob-carlborg** [comment]
Now when you mention it. I never ran the compiler, I only ran the installer and verified that it placed the correct files in the correct locations.

**Pull request merged**
