### PR TITLE
Fix sc.ini permissions issue on Windows 10

### PR DESCRIPTION
**Pull request by eco**

### CODE REVIEW

**Comment by CyberShadow** [comment]
If you upload an installer EXE, I can test it in an XP VM if you like.

**Comment by eco** [comment]
http://gnuk.net/dmd-2.069.2.exe

I might change this to just have it inherit the permissions like you mentioned in the other pull request.

**Comment by CyberShadow** [comment]
The installation seemed to have been completed successfully.

**Comment by eco** [comment]
A silent failure is pretty much exactly what we wanted to happen.

I've pushed a new version that follows you recommendation to inherit permissions instead of granting read to Users. I just did it on the whole installation directory to catch everything.

**Comment by rainers** [comment]
The problem is not specific to Windows 10, I can reproduce it with 8.1, and it should exist for all versions that allow restricted users including XP IIRC. `icacls` seems available starting with Windows 8, so it might not fit all cases. I think we should still support Windows 7, maybe by a fallback to `cacls`.

**Comment by CyberShadow** [comment]
@rainers Is there an AccessControl API to reset ACLs on a file? If so then we should use that.

**Comment by CyberShadow** [comment]
BTW, there should be a Bugzilla issue for this, linking to the forum thread and these discussions, and a link to the Bugzilla in a code comment.

**Comment by CyberShadow** [comment]
Would it be realistic to fix the root of the issue (the string replace function using a system temp directory) instead?

**Comment by CyberShadow** [comment]
Alternatively, does NSIS provide a way to copy a file's contents but not attributes?

**Comment by rainers** [comment]
Bugzilla entries are https://issues.dlang.org/show_bug.cgi?id=15456 and https://issues.dlang.org/show_bug.cgi?id=15572

**Comment by rainers** [comment]
> Would it be realistic to fix the root of the issue (the string replace function using a system temp directory) instead?

Seems easy: just replace
```
  GetTempFileName $R2               ; who's new?
```
with
```
  Push "$2.tmp"                     ; temp file in same directory
  Pop $R2
```
in ReplaceInFile.nsh

**Comment by rainers** [comment]
I also noticed that the file owner of sc.ini could not be displayed. Not going through the temp folder fixed that, too.
I've made a new PR with the change to ReplaceInFile.nsh: https://github.com/D-Programming-Language/installer/pull/167

**Comment by WalterBright** [comment]
> I think we should still support Windows 7

This exact problem was reported to me by a 64 Windows 7 Pro user.

In any case, we must still support Windows 7. A lot of developers are not wanting to move to newer versions of Windows.

**Comment by MartinNowak** [comment]
My understanding is that #167 supercedes this PR, so can it be closed?

**Comment by eco** [comment]
icacls is available in Windows 7. It has been included in every version of Windows since 2003. #167 works for me anyway, though.

**Comment by eco** [comment]
Ugh, sorry. I made a commit 63b9dc5015 accidentally (instead of a Pull Request). Normally when you hit Edit on Github it will make a pull request but apparently since I'm a committer on this repo it just went ahead and made a commit.

**Pull request closed without merging**
