### PR TITLE
update dmd.conf for new install location

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
LGTM

**Comment by MartinNowak** [comment]
> LGTM

Can you please test the updated installer?
https://dlang.dawg.eu/downloads/dmd.2.068.0-b2~fix14801/

**Comment by jacob-carlborg** [comment]
Crap, dmd.conf is for D1. I'll create a new PR.

**Comment by jacob-carlborg** [comment]
@MartinNowak please see #134. I apologise for the confusion.

**Pull request merged**
