### PR TITLE
update VisualD to latest stable 0.3.41

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
@rainers will 0.3.42 be ready soon? Might be nice b/c it fixes an issue with VS2015.
[Issue 14614 – PDB File Not Generated when building in VS2015](https://issues.dlang.org/show_bug.cgi?id=14614)

**Comment by rainers** [comment]
I think I can change the beta to a release (didn't hear about regressions). One "regression" that would be nice to avoid in a new version is support for the new AA implementation in mago. Unfortunately the _aaVersion symbol now disappears during linking. See https://github.com/D-Programming-Language/druntime/pull/1229#issuecomment-125479942

**Comment by rainers** [comment]
Prepared a release candidate: https://github.com/D-Programming-Language/visuald/releases/tag/v0.3.42-rc1
I've worked around the missing aaVersion by checking the existence of rt.aaa.fakeEntryTI that happens to be public.

**Comment by Zensin** [comment]
For now can we just run the current release installer, uncheck the VS integration box, and then install Visual D separately so it works with vs2015?

**Comment by rainers** [comment]
> For now can we just run the current release installer, uncheck the VS integration box, and then install Visual D separately so it works with vs2015?

Visual D works with VS2015, but linking an executable for x64 against the MS runtime library that comes with VS 2015 will fail due to changed symbols. You'll need to place the runtime libraries from older VS versions somewhere at the moment.

**Comment by MartinNowak** [comment]
Thanks, I updated the PR. Waiting for the final 0.3.42.

**Comment by MartinNowak** [comment]
What's the state of this @rainers? Release is planned on friday, should we go with 0.3.41 instead?

**Comment by rainers** [comment]
There have been a couple of downloads but no complains, so I guess I can make a release tonight. If there are no immediate regressions found, it should be good enough to be included.

**Comment by Zensin** [comment]
So I won't have to do anything special for vs2015 after tonight? Just download the current release of D and check VS integration? I'm using vs2015 on x64 windows. Please forgive my ignorance. I've never used D before. This will be my first time and I'd like to start off developing in vs2015.

**Comment by rainers** [comment]
@Zensin Latest Visual D will not be in the dmd installer before friday. You can get it now at https://github.com/D-Programming-Language/visuald/releases/tag/v0.3.42
Building 32-bit applications works, but due to changes in the VS2015 C runtime, building applications for x64 will not yet work.

**Comment by ZombineDev** [comment]
@MartinNowak This is ready to be merged. [Visual D 0.3.42 released](http://forum.dlang.org/post/mpttnn$n08$1@digitalmars.com)

**Comment by MartinNowak** [comment]
> So I won't have to do anything special for vs2015 after tonight?

Now, you'll have to use VS2013. We're still working on VS2015 compatibility.
We worked on integrating the VS setup into our installer (will be released with 2.069 https://github.com/D-Programming-Language/installer/pull/132), for now simply run http://go.microsoft.com/fwlink/?LinkId=517284. You can have VS2013 installed in parallel to VS2015.

**Comment by MartinNowak** [comment]
> Building 32-bit applications works, but due to changes in the VS2015 C runtime, building applications for x64 will not yet work.

Can we work on that ([card](https://trello.com/c/5OWcNIGy/33-windows-installer-vs2015-support)) and [mscoff libs](https://issues.dlang.org/show_bug.cgi?id=13889) right after the release @rainers? I don't want to get far behind VS.

**Comment by MartinNowak** [comment]
OK, I'll merge the version bump then.

**Comment by rainers** [comment]
> Can we work on that (card) and mscoff libs right after the release

Ok. I won't be able to do much the next couple of days, though.

**Comment by rainers** [comment]
> Can we work on ... mscoff libs right after the release

BTW: did you notice https://github.com/D-Programming-Language/installer/pull/122? I haven't tried it recently, though.

**Pull request merged**
