### PR TITLE
update dlang.org patch

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by CyberShadow** [comment]
What is this?

**Comment by MartinNowak** [comment]
It's a patch for the dlang.org repo necessary to build documentation for the release.
This is necessary because the prerelease/latest logic doesn't apply.

**Comment by CyberShadow** [comment]
Well, OK. But shouldn't it be integrated in the Makefile instead?

**Comment by CyberShadow** [comment]
I can't review this because I don't know anything about the system, but you have my OK (FWIW) to merge it yourself

**Comment by MartinNowak** [comment]
Ideally we'd add another target to the makefile, but the way it's structured makes it difficult, e.g. it clones the repos again and builds the compiler.

**Comment by MartinNowak** [comment]
It also removes a few menu points that don't apply to the released docs.

**Pull request merged**
